---
title: "Cleaning Final Project Code"
author: "Rena Cohen"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
View(afta_raw)
```

```{r}
afta_raw <- as.data.frame(afta_raw)
View(afta_raw)

afta_1 <- afta_raw %>%
  
  # Renaming lots of columns to not the survey questions
  
  rename(date = 2, city = 4, state = 5, zip_code = 6, purpose = 7,
         budget = 9, legal_status = 10, presenter = 12, canceled_events = 13,
         lost_attendees_1 = 15, lost_attendees_2 = 16, lost_revenue_admissions = 22, 
         lost_revenue_admissions_amt = 24, lost_revenue_non_admissions=25, 
         lost_revenue_non_admissions_amt = 27, new_expenditures = 28, 
         new_expenditures_amt = 29, proj_loss_date = 31, 
         online_presence = 32, financial_reserves = 33, reduced_payroll = 34, 
         laid_off_staff = 35, laid_off_artists = 36, laid_off_other = 37, 
         hiring_freeze = 38, bounce_back_21 = 42, laid_off_staff_amt = 43,
         furloughed_staff_amt = 44,laid_off_artist_amt = 45,
         furloughed_artist_amt = 46, laid_off_other_amt = 47,
         furloughed_other_amt = 48, likelihood_staff_reduction = 50,
         applied_for_assistance = 51, current_status = 60, concern_late_payment = 61,
         concern_limited_savings = 62, concern_payroll_inability = 63, 
         concern_bill_inability = 64, concern_cancelled_contracts = 65, 
         concern_reduced_donations = 66, concern_business_closure = 67, 
         financial_impact_severity = 69, survival = 70, reopened = 81, reopening_date = 82,
         target_reopening_date = 83, reopening_plan = 93) %>%

# remember to merge 15 and 16 at some point, they're the same
  
  #removing some irrelevant rows 
  
  select(-c(1,3,8,14, 11, 17, 18, 19, 20, 21, 23, 26,29, 30, 39:41, 49, 52:59, 
            68, 71, 72:75, 76:80, 84:92, 94:ncol(afta_raw))) %>%
  
  # Creating my date variable in a usable format
  
  mutate(date = mdy_hms(date)) %>%
  
  # Chopping off the time survey data on date so that merge will be easier
  
  mutate(date = str_sub(date, 1, 10)) %>%
  mutate(date = ymd(date)) %>%
  
  # Shortening Legal Status inputs
  mutate(nonprofit = ifelse(legal_status == "Nonprofit / private organization (e.g. 501c3)", T, F)) %>%

# Re-fashioning survival to delete extra characters

mutate(survival = str_sub(survival, 1, 1)) %>%

# Same for applied_for_assistance
  
  mutate(applied_for_assistance = str_sub(applied_for_assistance, 1, 1)) %>%
  
  # Changing a bunch of checkbox variables into true/falses
  
  mutate(online_presence = ifelse(is.na(online_presence), F, T)) %>%
  mutate(financial_reserves = ifelse(is.na(financial_reserves), F, T)) %>%
  mutate(reduced_payroll = ifelse(is.na(reduced_payroll), F, T)) %>%
  mutate(laid_off_staff = ifelse(is.na(laid_off_staff), F, T)) %>%
  mutate(laid_off_artists = ifelse(is.na(laid_off_artists), F, T)) %>%
  mutate(laid_off_other = ifelse(is.na(laid_off_other), F, T))%>%
  
  # Getting rid of the dollar signs in the lost revenue amounts
  
   mutate(lost_revenue_admissions_amt = as.numeric(str_sub(lost_revenue_admissions_amt, 2, -1))) %>%
   mutate(lost_revenue_non_admissions_amt = as.numeric(str_sub(lost_revenue_non_admissions_amt, 2, -1)))

glimpse(afta_1$lost_attendees_1)
glimpse(afta_raw$)
  
View(afta_1)

# Playing around
  test <- afta_1 %>%
  filter(!is.na(lost_revenue_admissions_amt)) %>%
    mutate(lost_revenue_admissions_amt = str_sub(lost_revenue_admissions_amt, 2, -1)) %>%
    mutate(lost = as.numeric(lost_revenue_admissions_amt)) %>%
    filter(!is.na(lost))
  
  
  
test$lost
    
    mutate(lost_revenue_admissions_amt = as.numeric(lost_revenue_admissions_amt))
  
  View(test)
  
  ggplot(test, aes(x = lost, fill = survival)) +
    geom_histogram(bins = 15) +
    xlim(0,1000000) +
    ylim(0,300) +
    facet_wrap(~survival)
    
  
  saveRDS(afta_1, file = "afta_1.RDS")
  
  afta_1 <- readRDS("afta_1.RDS")
  
View(afta_1)
test2<- test %>%
  filter(!is.na(likelihood_staff_reduction))
dim(test2)
test2$likelihood_staff_reduction
ggplot(test, )
  
```


```{r}
# Exploring our COVID data

covid <- read_csv("covid.csv")
covid_cleaner <- covid %>%
  select(date, state, deathIncrease, positiveIncrease, death, positive) %>%
  mutate(date = ymd(date)) %>%
  rename(abbreviation = state)

state_abbreviations <- read_csv("state_abbreviations.csv")
state_abbreviations_new <- state_abbreviations %>%
  rename(abbreviation = 3, state = 2)

covid_states_merge <- inner_join(state_abbreviations_new, covid_cleaner, by = "abbreviation") %>%
  select(date, state, deathIncrease, positiveIncrease, abbreviation, death, positive)

View(covid_states_merge)




```


```{r}
library(readxl)
afta_data_new <- read_excel("afta_data_new_columns.xlsx", col_types = c("text", "text",
                            "text", "text", "text", "text", "text", "text", "text",
                            "text", "numeric", "text", "numeric", "text", "numeric", "text", 
                            "numeric", "text", "text", "text", "text", "text",
                            "text", "skip", "text", "numeric", "numeric", "numeric", 
                            "numeric", "numeric", "text", "text", "text", "text",
                            "text", "text", "text",  "text",  "text", "numeric", 
                            "skip", "skip", "skip", "skip", "skip", "skip", "skip"))


# Cleaning some data now that it's read in 

# I will begin by formatting the dates properly. Here are the survey dates

afta_data_clean <- afta_data_new %>%
  mutate(date = mdy_hms(date) )%>%
  mutate(date = str_sub(date, 1, 10)) %>%
  mutate(date = ymd(date)) %>%

  # Next, I have a ton of variables that would work best as logicals, so I will 
  # format them as such using mutate
  
  
  mutate(used_financial_reserves = ifelse(is.na(used_financial_reserves), F, T)) %>%
  mutate(reduced_salaries = ifelse(is.na(reduced_salaries), F, T)) %>%
  mutate(laid_off_staff = ifelse(is.na(laid_off_staff), F, T)) %>%
  mutate(laid_off_artists = ifelse(is.na(laid_off_artists), F, T))  %>%
  mutate(hiring_freeze = ifelse(is.na(hiring_freeze), F, T)) %>%
  mutate(late_payments = ifelse(is.na(late_payments), F, T)) %>%
  mutate(limited_savings = ifelse(is.na(limited_savings), F, T)) %>%
  mutate(inability_making_payroll = ifelse(is.na(inability_making_payroll), F, T)) %>%
  mutate(inability_paying_bills = ifelse(is.na(inability_paying_bills), F, T)) %>%
  mutate(cancelled_contracts = ifelse(is.na(cancelled_contracts), F, T)) %>%
  mutate(business_closure = ifelse(is.na(business_closure), F, T))  %>%
  mutate(reduced_philanthropy = ifelse(is.na(`Reduced philanthropic giving:Which of the following are currently major financial concerns for your organization? (Check all that apply.)`), F, T)) %>%
  mutate(increase_online_presence = ifelse(is.na(increase_online_presence), F, T)) %>%
  select(-"Reduced philanthropic giving:Which of the following are currently major financial concerns for your organization? (Check all that apply.)") %>%

# Adding a variable that takes the total lost revenue

  mutate(lost_revenue_total = lost_revenue_admissions_amt + lost_revenue_non_admissions_amt)


# The data is more or less clean now. Time to start adding interesting new variables that
# can maybe be seen over time! 



ggplot(afta_data_clean, aes(x = lost_attendees, y = lost_revenue_admissions_amt)) +
  geom_point() +
  ylim(0,10e6) +
  xlim(0,10e4)



```
```{r}
# Merging our AFTA data and our COVID data

afta_covid <- inner_join(covid_states_merge, afta_data_clean, by = c("state", "date"))
View(afta_covid)

smaller_afta_covid <- afta_covid %>%
  group_by(state) %>%
  summarise(num = n(), )



big_states <- afta_covid %>%
  group_by(state) %>%
  summarise(closures = mean(business_closure), financial_impact = mean(severity_financial_impact))

ggplot(big_states, aes(x = closures, y = financial_impact))+
  geom_point()

# did organizations feel things immediately, or did mean financial impact increase over time?

dates <- afta_covid %>%
  group_by(date) %>%
  summarise(number_respondents = n())

ggplot(dates, aes(x = date, y = number_respondents)) +
  geom_point()


org_size <- afta_covid %>%
  group_by(budget) %>%
  summarise(mean_rev_lost= mean(lost_revenue_total, na.rm = T)) 

ggplot(afta_covid, aes(y = lost_revenue_total, fill = fct_reorder(budget, lost_revenue_total, .fun = "mean", na.rm = T)))+
  geom_boxplot() +
  ylim(0, 1000000) +
  labs(title = "Lost Revenue due to COVID in Arts Organizations of Different Sizes",
       x = "", y = "Total Lost Revenue") +
  scale_fill_discrete(name = "Organization Budget") 
```

